### PR TITLE
Create ANG-DIFF_Alabama_LocC_LocD.ini

### PR DESCRIPTION
**Pull request by omid-cs**

### CODE REVIEW

**Comment by immesys** [comment]
Sorry, I cannot accept a pull request into production. Could you rather move this to QA? By adding the file, it gets automatically run.

**Comment by immesys** [comment]
Of course, QA probably doesn't have this data. The point is for you to get some experience on a server that is not mission-critical. Leave this PR here and make another INI file on QA just to get a feel for it. If you still feel comfortable with this PR after that, I will merge it.

**Comment by omid-cs** [comment]
Sure, I was trying to create a distillate for Alabama which seems to be absent from QA. This is the only location that has two adjacent uPMUs and is therefore a good candidate for our analytics application.

I certainly make a few other distillates for locations that are on QA to get experience and will send another pull request for PR in a few days.

**Comment by omid-cs** [comment]
Michael, could you please merge if you are finished with the maintenance of the server?

**Pull request closed without merging**
